CREATE TABLE IF NOT EXISTS films (
  film_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar NOT NULL,
  description varchar(200),
  releaseDate timestamp,
  duration integer,
  rating_id integer
);

CREATE TABLE IF NOT EXISTS genre (
  genre_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar
);

CREATE TABLE IF NOT EXISTS film_multi_genre (
  film_multi_genre_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  film_id integer,
  genre_id integer
);

CREATE TABLE IF NOT EXISTS film_likes (
  film_likes_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  film_id integer,
  user_id integer
);

CREATE TABLE IF NOT EXISTS rating_film (
  rating_film_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  description varchar
);

CREATE TABLE IF NOT EXISTS users (
  user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar NOT NULL,
  login varchar NOT NULL,
  name varchar NOT NULL,
  birthday timestamp
);

CREATE TABLE IF NOT EXISTS friends_user (
  friends_user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  friend_user_id integer NOT NULL,
  status_id integer
);

CREATE TABLE IF NOT EXISTS status (
  status_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar
);

ALTER TABLE films ADD FOREIGN KEY (rating_id) REFERENCES rating_film (rating_film_id) ON DELETE CASCADE;

ALTER TABLE film_multi_genre ADD FOREIGN KEY (genre_id) REFERENCES genre (genre_id) ON DELETE CASCADE;

ALTER TABLE film_multi_genre ADD FOREIGN KEY (film_id) REFERENCES films (film_id) ON DELETE CASCADE;

ALTER TABLE film_likes ADD FOREIGN KEY (film_id) REFERENCES films (film_id) ON DELETE CASCADE;

ALTER TABLE film_likes ADD FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE;

ALTER TABLE friends_user ADD FOREIGN KEY (status_id) REFERENCES status (status_id) ON DELETE CASCADE;

ALTER TABLE friends_user ADD FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE;

ALTER TABLE friends_user ADD FOREIGN KEY (friend_user_id) REFERENCES users (user_id) ON DELETE CASCADE;